ALTER TYPE "PublicationProposalSourceType" ADD VALUE 'P9_OPTIMIZATION_PLAN';
ALTER TYPE "PublicationExecutionStatus" ADD VALUE 'AUTOMATION_AUTHORIZED' AFTER 'APPROVED';
ALTER TYPE "PublicationExecutionEventType" ADD VALUE 'AUTOMATION_AUTHORIZED' AFTER 'APPROVED';
