export const OPTIMIZATION_FEEDBACK_SCOPE_VERSION = 'OPTIMIZATION_FEEDBACK_SCOPE_V1' as const;
export const OPTIMIZATION_FEEDBACK_EVIDENCE_VERSION = 'OPTIMIZATION_FEEDBACK_EVIDENCE_V1' as const;
export const OPTIMIZATION_FEEDBACK_PROFILE_VERSION = 'OPTIMIZATION_FEEDBACK_PROFILE_V1' as const;
export const OPTIMIZATION_FEEDBACK_WINDOW_LIMIT = 20 as const;

export type FeedbackMarketScopeMode =
  | 'CONFIGURED_MARKET'
  | 'UNCONFIGURED_LEGACY';

export type FeedbackEffect = 'POSITIVE' | 'NEUTRAL' | 'NEGATIVE';
