ALTER TYPE "SearchFactProvider" ADD VALUE 'GOOGLE_SERP';
ALTER TYPE "SearchFactProvider" ADD VALUE 'BING_SERP';
ALTER TYPE "SearchFactKind" ADD VALUE 'QUERY_PAGE_RANK';
ALTER TYPE "SearchFactMetricSemantic" ADD VALUE 'CURRENT_SERP_POSITION';
ALTER TYPE "SearchFactSourceKind" ADD VALUE 'REALTIME_SERP_OBSERVATION';
