import type { GeoRuleDefinition } from './geo.types.js';

export const BUILTIN_GEO_RULES = [
  {
    ruleCode: 'CITABILITY_NO_CLEAR_H1',
    name: 'No clear primary heading',
    category: 'Citability',
    description: 'The page does not expose one clear primary H1 heading from stored page facts.',
    version: 1,
    dimension: 'CITABILITY',
    severity: 'HIGH',
    weight: 2.5,
    detectionType: 'PAGE_FACT',
    detectionConfig: { expectedH1Count: 1 },
    geoImpact: 'A clear primary heading improves structural identity and extraction context for downstream systems.',
    fixGuide: 'Expose one descriptive H1 that accurately identifies the page topic without duplicating template headings.'
  },
  {
    ruleCode: 'CITABILITY_HEADING_STRUCTURE_WEAK',
    name: 'Weak heading structure',
    category: 'Citability',
    description: 'Stored heading counts indicate limited or unclear document hierarchy for a substantive page.',
    version: 1,
    dimension: 'CITABILITY',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PAGE_FACT',
    detectionConfig: { substantiveWordCount: 400 },
    geoImpact: 'Predictable heading hierarchy makes long pages easier to segment into extractable topical units.',
    fixGuide: 'Organize substantive content with descriptive H2/H3 sections while preserving a single clear H1.'
  },
  {
    ruleCode: 'CITABILITY_NO_SUMMARY_BLOCK',
    name: 'Summary block not evidenced',
    category: 'Citability',
    description: 'No deterministic summary or answer-first block evidence is available for the page.',
    version: 1,
    dimension: 'CITABILITY',
    severity: 'LOW',
    weight: 1,
    detectionType: 'PAGE_FACT',
    geoImpact: 'Concise introductory summaries can make core claims easier to extract when they are factually identifiable.',
    fixGuide: 'Add a concise factual summary near the main heading when the page purpose benefits from an answer-first introduction.'
  },
  {
    ruleCode: 'CITABILITY_LONG_UNBROKEN_SECTION',
    name: 'Long content lacks evidenced segmentation',
    category: 'Citability',
    description: 'A long page has insufficient deterministic heading segmentation relative to its stored word count.',
    version: 1,
    dimension: 'CITABILITY',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PAGE_FACT',
    detectionConfig: { wordCount: 1200, minimumSectionHeadings: 2 },
    geoImpact: 'Large unsegmented blocks reduce deterministic extractability and make topical boundaries less explicit.',
    fixGuide: 'Split long content into coherent sections with descriptive headings that match the actual topic transitions.'
  },
  {
    ruleCode: 'CITABILITY_LOW_FACT_SIGNAL',
    name: 'Factual density unavailable or weak',
    category: 'Citability',
    description: 'Deterministic factual-density evidence is unavailable or below the implemented readiness threshold.',
    version: 1,
    dimension: 'CITABILITY',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PAGE_FACT',
    geoImpact: 'Explicit factual statements improve the usefulness of content as a source when they can be verified from stored evidence.',
    fixGuide: 'Strengthen concrete facts, definitions, figures or sourced claims where appropriate; keep the outcome UNKNOWN until facts are measurable.'
  },
  {
    ruleCode: 'CITABILITY_NO_SOURCE_LINKS',
    name: 'No source links observed',
    category: 'Citability',
    description: 'The page has no observed external source-link signal in the stored crawl facts.',
    version: 1,
    dimension: 'CITABILITY',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PAGE_FACT',
    geoImpact: 'Relevant source links can make factual provenance more explicit even though P3 does not judge source authority semantically.',
    fixGuide: 'Link important factual claims to appropriate primary or authoritative references when the page relies on external evidence.'
  },
  {
    ruleCode: 'CITABILITY_NO_DEFINITION_PATTERN',
    name: 'Definition pattern not evidenced',
    category: 'Citability',
    description: 'No deterministic definition-pattern evidence is available for content that may require explicit definitions.',
    version: 1,
    dimension: 'CITABILITY',
    severity: 'LOW',
    weight: 1,
    detectionType: 'PAGE_FACT',
    geoImpact: 'Explicit definitions can improve extraction clarity for concepts when a deterministic definition can be identified.',
    fixGuide: 'Define important concepts directly where useful; do not infer semantic definition quality without measurable evidence.'
  },
  {
    ruleCode: 'CITABILITY_TABLE_LIST_ABSENT_WHEN_STRUCTURED_CONTENT_EXISTS',
    name: 'Structured presentation not evidenced',
    category: 'Citability',
    description: 'Structured list or table presentation is not evidenced for content that has a deterministic structured-content signal.',
    version: 1,
    dimension: 'CITABILITY',
    severity: 'LOW',
    weight: 1,
    detectionType: 'PAGE_FACT',
    geoImpact: 'Lists and tables can improve machine extraction when the underlying content is naturally structured.',
    fixGuide: 'Use semantic lists or tables for genuinely structured facts; return UNKNOWN when the crawler has no structural evidence.'
  },
  {
    ruleCode: 'CITABILITY_PAGE_TOO_THIN',
    name: 'Page too thin for citation readiness',
    category: 'Citability',
    description: 'An indexable HTML page contains too little stored textual content for the readiness threshold.',
    version: 1,
    dimension: 'CITABILITY',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PAGE_FACT',
    detectionConfig: { minimumWords: 200 },
    geoImpact: 'Very limited content can reduce the amount of extractable context available to downstream retrieval systems.',
    fixGuide: 'Expand useful original coverage only when the page purpose requires more context; avoid padding pages with filler.'
  },
  {
    ruleCode: 'CITABILITY_CANONICAL_IDENTITY_WEAK',
    name: 'Canonical page identity is weak',
    category: 'Citability',
    description: 'An eligible page lacks a stable canonical URL fact or has an unresolved indexability identity.',
    version: 1,
    dimension: 'CITABILITY',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PAGE_FACT',
    geoImpact: 'Stable canonical identity helps downstream systems associate extracted statements with one preferred page URL.',
    fixGuide: 'Expose a correct canonical URL for the preferred indexable page and verify it remains reachable and consistent.'
  },

  {
    ruleCode: 'ENTITY_ORGANIZATION_MISSING',
    name: 'Organization entity missing',
    category: 'Entity',
    description: 'No deterministic organization identity has been observed from structured or configured project signals.',
    version: 1,
    dimension: 'ENTITY',
    severity: 'HIGH',
    weight: 2.5,
    detectionType: 'PROJECT_AGGREGATE',
    geoImpact: 'A stable organization identity provides a primary entity anchor for publisher, brand and relationship data.',
    fixGuide: 'Provide explicit Organization structured data or configured project identity with a stable name and official URL.'
  },
  {
    ruleCode: 'ENTITY_CANONICAL_NAME_INCONSISTENT',
    name: 'Canonical entity name is inconsistent',
    category: 'Entity',
    description: 'Deterministic identity observations contain conflicting canonical names for the same owned entity.',
    version: 1,
    dimension: 'ENTITY',
    severity: 'HIGH',
    weight: 2,
    detectionType: 'ENTITY_FACT',
    geoImpact: 'Consistent naming reduces ambiguity when the same entity appears across schema, metadata and owned pages.',
    fixGuide: 'Standardize the official entity name across structured data, publisher metadata and primary owned identity pages.'
  },
  {
    ruleCode: 'ENTITY_OFFICIAL_URL_MISSING',
    name: 'Official entity URL missing',
    category: 'Entity',
    description: 'A deterministic entity record has no official URL from owned or structured signals.',
    version: 1,
    dimension: 'ENTITY',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'ENTITY_FACT',
    geoImpact: 'An official URL gives entity references a stable web identity and a direct owned source.',
    fixGuide: 'Attach the entity to its canonical official URL through explicit structured or project identity data.'
  },
  {
    ruleCode: 'ENTITY_SAMEAS_MISSING',
    name: 'Entity sameAs links missing',
    category: 'Entity',
    description: 'The entity has no deterministic sameAs identity links in its structured observations.',
    version: 1,
    dimension: 'ENTITY',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'ENTITY_FACT',
    geoImpact: 'Explicit sameAs links can connect an owned entity identity to other canonical profiles without semantic guessing.',
    fixGuide: 'Add accurate sameAs references for official profiles where they genuinely represent the same entity.'
  },
  {
    ruleCode: 'ENTITY_PUBLISHER_MISSING',
    name: 'Publisher entity missing',
    category: 'Entity',
    description: 'No explicit publisher relationship is observed for eligible published content.',
    version: 1,
    dimension: 'ENTITY',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'ENTITY_FACT',
    geoImpact: 'Publisher relationships make content ownership and attribution more explicit for downstream consumers.',
    fixGuide: 'Expose the publisher using appropriate structured data or explicit owned metadata on published content.'
  },
  {
    ruleCode: 'ENTITY_AUTHOR_UNCLEAR',
    name: 'Author identity unclear',
    category: 'Entity',
    description: 'Eligible authored content lacks a deterministic author identity observation.',
    version: 1,
    dimension: 'ENTITY',
    severity: 'LOW',
    weight: 1,
    detectionType: 'ENTITY_FACT',
    geoImpact: 'Explicit author identity improves attribution clarity when content is presented as authored material.',
    fixGuide: 'Expose a real author identity and profile relationship where authorship is materially relevant to the content.'
  },
  {
    ruleCode: 'ENTITY_SCHEMA_ID_MISSING',
    name: 'Structured entity identifier missing',
    category: 'Entity',
    description: 'A structured entity lacks a stable identifier such as an appropriate @id value.',
    version: 1,
    dimension: 'ENTITY',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'ENTITY_FACT',
    geoImpact: 'Stable structured identifiers make repeated references to the same entity easier to connect deterministically.',
    fixGuide: 'Use a stable canonical identifier for important structured entities and reuse it consistently across related markup.'
  },
  {
    ruleCode: 'ENTITY_DUPLICATE_IDENTITY',
    name: 'Duplicate entity identity observed',
    category: 'Entity',
    description: 'Multiple deterministic entity records appear to represent the same normalized owned identity.',
    version: 1,
    dimension: 'ENTITY',
    severity: 'HIGH',
    weight: 2,
    detectionType: 'PROJECT_AGGREGATE',
    geoImpact: 'Duplicate identities can fragment observations and relationships that should point to one canonical entity.',
    fixGuide: 'Consolidate duplicated structured identities around one canonical name, URL and stable identifier.'
  },
  {
    ruleCode: 'ENTITY_RELATIONSHIP_SPARSE',
    name: 'Entity relationships are sparse',
    category: 'Entity',
    description: 'Important entities have few deterministic owned relationships available in the entity graph.',
    version: 1,
    dimension: 'ENTITY',
    severity: 'LOW',
    weight: 1,
    detectionType: 'PROJECT_AGGREGATE',
    geoImpact: 'Explicit relationships can clarify how organizations, people, products and services connect to each other.',
    fixGuide: 'Add accurate structured relationships where the relationship is factual and already represented by the site.'
  },
  {
    ruleCode: 'ENTITY_ABOUT_PAGE_MISSING',
    name: 'About identity page missing',
    category: 'Entity',
    description: 'No deterministic owned page has been identified as an about or organization identity page.',
    version: 1,
    dimension: 'ENTITY',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PROJECT_AGGREGATE',
    geoImpact: 'A dedicated identity page gives users and machines a stable owned location for organization context.',
    fixGuide: 'Provide an accessible about or organization page that clearly states the official identity and relevant facts.'
  },

  {
    ruleCode: 'BRAND_SITE_NAME_INCONSISTENT',
    name: 'Site name is inconsistent',
    category: 'Brand',
    description: 'Owned title, metadata, schema or configured identity signals use inconsistent site or brand names.',
    version: 1,
    dimension: 'BRAND',
    severity: 'HIGH',
    weight: 2,
    detectionType: 'PROJECT_AGGREGATE',
    geoImpact: 'Consistent owned naming strengthens deterministic brand identity across pages and structured metadata.',
    fixGuide: 'Standardize the official site or brand name across configuration, metadata and structured identity signals.'
  },
  {
    ruleCode: 'BRAND_ORGANIZATION_SCHEMA_MISSING',
    name: 'Organization schema missing for brand identity',
    category: 'Brand',
    description: 'No Organization structured-data observation supports the owned brand identity.',
    version: 1,
    dimension: 'BRAND',
    severity: 'HIGH',
    weight: 2,
    detectionType: 'PROJECT_AGGREGATE',
    geoImpact: 'Organization structured data gives the owned brand a machine-readable identity anchor.',
    fixGuide: 'Add accurate Organization structured data with official name, URL and stable identifier on an appropriate page.'
  },
  {
    ruleCode: 'BRAND_CONTACT_IDENTITY_MISSING',
    name: 'Contact identity missing',
    category: 'Brand',
    description: 'Owned pages do not provide a deterministic contact identity signal linked to the organization.',
    version: 1,
    dimension: 'BRAND',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PROJECT_AGGREGATE',
    geoImpact: 'Consistent contact identity supports owned-site trust and makes organization details easier to verify.',
    fixGuide: 'Provide accurate contact identity information and keep organization naming consistent with structured data.'
  },
  {
    ruleCode: 'BRAND_SOCIAL_IDENTITY_UNLINKED',
    name: 'Official profile identity is unlinked',
    category: 'Brand',
    description: 'No deterministic official-profile links are connected to the owned brand identity.',
    version: 1,
    dimension: 'BRAND',
    severity: 'LOW',
    weight: 1,
    detectionType: 'PROJECT_AGGREGATE',
    geoImpact: 'Explicit official-profile links can strengthen deterministic identity consistency without inferring external reputation.',
    fixGuide: 'Link only genuine official profiles through accurate sameAs or owned contact/profile references.'
  },
  {
    ruleCode: 'BRAND_ABOUT_PAGE_MISSING',
    name: 'Brand about page missing',
    category: 'Brand',
    description: 'No accessible owned about page is evidenced for the brand or organization.',
    version: 1,
    dimension: 'BRAND',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PROJECT_AGGREGATE',
    geoImpact: 'An owned about page provides a stable place for brand identity, history and organizational context.',
    fixGuide: 'Publish a clear about or organization page and connect it to consistent site-wide identity signals.'
  },
  {
    ruleCode: 'BRAND_PUBLISHER_IDENTITY_INCONSISTENT',
    name: 'Publisher identity is inconsistent',
    category: 'Brand',
    description: 'Publisher observations conflict with the configured or structured owned brand identity.',
    version: 1,
    dimension: 'BRAND',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PROJECT_AGGREGATE',
    geoImpact: 'Consistent publisher identity improves attribution continuity across owned published pages.',
    fixGuide: 'Align publisher names, identifiers and official URLs with the canonical organization identity.'
  },

  {
    ruleCode: 'AI_CRAWLER_ROBOTS_BLOCKED',
    name: 'AI crawler blocked by robots policy',
    category: 'AI Crawler',
    description: 'Stored robots policy facts explicitly disallow a supported crawler identity.',
    version: 1,
    dimension: 'AI_CRAWLER',
    severity: 'HIGH',
    weight: 2.5,
    detectionType: 'CRAWL_FACT',
    geoImpact: 'An explicit robots disallow can prevent that crawler identity from accessing affected URLs.',
    fixGuide: 'Review the site policy intentionally; allow the crawler only when it matches the organization’s publishing and access policy.'
  },
  {
    ruleCode: 'AI_CRAWLER_META_BLOCKED',
    name: 'AI crawler blocked by page directives',
    category: 'AI Crawler',
    description: 'Stored page-level robots or header directives explicitly block an implemented crawler access mode.',
    version: 1,
    dimension: 'AI_CRAWLER',
    severity: 'HIGH',
    weight: 2,
    detectionType: 'CRAWL_FACT',
    geoImpact: 'Explicit page directives can make otherwise reachable content unavailable to a supported crawler policy.',
    fixGuide: 'Audit page and header directives and change them only when broader crawler access is deliberately intended.'
  },
  {
    ruleCode: 'AI_CRAWLER_POLICY_UNKNOWN',
    name: 'AI crawler policy is unknown',
    category: 'AI Crawler',
    description: 'Stored facts are insufficient to determine the effective policy for a supported crawler identity.',
    version: 1,
    dimension: 'AI_CRAWLER',
    severity: 'LOW',
    weight: 1,
    detectionType: 'CRAWL_FACT',
    geoImpact: 'Unknown policy reduces confidence in technical readiness reporting and should remain explicitly unknown.',
    fixGuide: 'Refresh factual robots, meta and header observations; do not convert missing policy evidence into an assumed allow or block.'
  },
  {
    ruleCode: 'AI_CRAWLER_UNREACHABLE',
    name: 'Crawler target is unreachable',
    category: 'AI Crawler',
    description: 'Stored HTTP facts show that the evaluated content is not factually reachable for readiness evaluation.',
    version: 1,
    dimension: 'AI_CRAWLER',
    severity: 'HIGH',
    weight: 2,
    detectionType: 'CRAWL_FACT',
    geoImpact: 'Content that cannot be reached cannot be reliably evaluated for downstream crawler readiness.',
    fixGuide: 'Resolve factual transport, server or access failures and recrawl before drawing conclusions about crawler readiness.'
  },

  {
    ruleCode: 'CONTENT_GEO_HEADING_STRUCTURE_WEAK',
    name: 'Content heading hierarchy is weak',
    category: 'Content GEO',
    description: 'Stored heading facts indicate weak hierarchy for an eligible substantive page.',
    version: 1,
    dimension: 'CONTENT_GEO',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PAGE_FACT',
    geoImpact: 'Well-structured headings improve deterministic segmentation and topical navigation of long content.',
    fixGuide: 'Use a clear H1 and descriptive section headings that follow the actual information hierarchy.'
  },
  {
    ruleCode: 'CONTENT_GEO_SUMMARY_ABSENT',
    name: 'Content summary not evidenced',
    category: 'Content GEO',
    description: 'A deterministic summary signal is not available for the eligible content page.',
    version: 1,
    dimension: 'CONTENT_GEO',
    severity: 'LOW',
    weight: 1,
    detectionType: 'PAGE_FACT',
    geoImpact: 'A concise summary can surface the page’s main answer or scope when the signal is deterministically measurable.',
    fixGuide: 'Add a factual introductory summary where appropriate; keep this rule UNKNOWN until the crawler can identify the signal.'
  },
  {
    ruleCode: 'CONTENT_GEO_STRUCTURED_ELEMENTS_ABSENT',
    name: 'Structured content elements not evidenced',
    category: 'Content GEO',
    description: 'No deterministic list or table structural evidence is available where structured presentation may be useful.',
    version: 1,
    dimension: 'CONTENT_GEO',
    severity: 'LOW',
    weight: 1,
    detectionType: 'PAGE_FACT',
    geoImpact: 'Semantic lists and tables can expose structured facts more clearly when the content genuinely has tabular or list form.',
    fixGuide: 'Use semantic lists or tables for naturally structured information and avoid fabricating this signal when it is not measurable.'
  },
  {
    ruleCode: 'CONTENT_GEO_SOURCE_LINKS_MISSING',
    name: 'Reference links missing',
    category: 'Content GEO',
    description: 'Stored page facts show no external reference-link signal on an eligible substantive page.',
    version: 1,
    dimension: 'CONTENT_GEO',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PAGE_FACT',
    geoImpact: 'Appropriate reference links make externally sourced factual claims easier to trace without requiring semantic source scoring.',
    fixGuide: 'Cite relevant primary or authoritative references when external facts materially support the page.'
  },
  {
    ruleCode: 'CONTENT_GEO_AUTHOR_PUBLISHER_MISSING',
    name: 'Author or publisher identity missing',
    category: 'Content GEO',
    description: 'Eligible published content lacks deterministic author or publisher identity evidence.',
    version: 1,
    dimension: 'CONTENT_GEO',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PAGE_FACT',
    geoImpact: 'Explicit authorship or publisher identity improves attribution clarity for published content.',
    fixGuide: 'Expose accurate author and/or publisher metadata where it is relevant to the page’s publishing context.'
  },
  {
    ruleCode: 'CONTENT_GEO_STRUCTURED_DATA_MISSING',
    name: 'Relevant structured data missing',
    category: 'Content GEO',
    description: 'An eligible page has no observed structured-data signal from the stored crawl facts.',
    version: 1,
    dimension: 'CONTENT_GEO',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PAGE_FACT',
    geoImpact: 'Accurate structured data can make page type, publisher and entity relationships more explicit to machine consumers.',
    fixGuide: 'Add only schema types that accurately represent the page and validate that required properties match visible content.'
  },
  {
    ruleCode: 'CONTENT_GEO_CANONICAL_MISSING',
    name: 'Canonical URL missing for GEO content',
    category: 'Content GEO',
    description: 'An eligible indexable page has no stored canonical URL fact.',
    version: 1,
    dimension: 'CONTENT_GEO',
    severity: 'MEDIUM',
    weight: 1.5,
    detectionType: 'PAGE_FACT',
    geoImpact: 'A canonical URL provides a stable preferred identity for content that may be retrieved or referenced downstream.',
    fixGuide: 'Expose the correct canonical URL for the preferred indexable version and keep internal identity signals aligned.'
  },
  {
    ruleCode: 'CONTENT_GEO_NOT_INDEXABLE',
    name: 'Content is not indexable',
    category: 'Content GEO',
    description: 'Stored deterministic indexability facts show that the page is not eligible for normal indexing.',
    version: 1,
    dimension: 'CONTENT_GEO',
    severity: 'HIGH',
    weight: 2,
    detectionType: 'PAGE_FACT',
    geoImpact: 'Non-indexable content has reduced readiness for retrieval-oriented discovery even when the page remains directly reachable.',
    fixGuide: 'Confirm whether non-indexability is intentional; remove blocking directives only when the page should be discoverable.'
  }
] as const satisfies readonly GeoRuleDefinition[];
